delete http://localhost:3000/pessoas/1 HTTP/1.1
Content-Type: application/json

{
  "nome" : "Alice Tecnologia",
	"cpf" : "111.111.111-11",
	"data_nascimento" : "1995-01-15",
	"telefone" : "11 1111-1111",
	"endereco" : "Rua A, 123",
	"altura" : 1.65,
	"peso" : 60
}

###

GET http://localhost:3000/pessoas

###